language: elixir
elixir:
  - 1.3.2
otp_release:
  - 19.0.0
notifications:
  recipients:
    - ricn@rny.io
before_install:
  - sudo apt-get install libreoffice
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
after_success:
  - "mix compile && mix coveralls.travis"
