language: elixir
otp_release:
  - 18.2
notifications:
  recipients:
    - ricn@rny.io
before_install:
  - sudo apt-get install libreoffice
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
after_success:
  - "mix compile && mix coveralls.travis"
